definitions:
  entities.AddUser:
    properties:
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
      role:
        type: integer
    type: object
info:
  contact: {}
paths:
  /users:
    get:
      description: Retrieve a list of users from the system
      parameters:
      - description: Authorization Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get list of users
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: Create a new user in the system
      parameters:
      - description: Authorization Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Add User Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entities.AddUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Add a new user
      tags:
      - Users
  /users/{id}:
    delete:
      description: Remove a user from the system by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: Authorization Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Delete a user
      tags:
      - Users
swagger: "2.0"
